update PGI compiler support to detect when special template handling is needed
- added autoconf detection of support for --one_instantiation_per_object
- updated Makefiles to do the right thing based on config

diff --git a/xplat/configure b/xplat/configure
--- a/xplat/configure
+++ b/xplat/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT BUILDSHARED VERBOSEMAKE COMPILER_TYPE AR ARFLAGS SOFLAGS SET_MAKE RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CXXCPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT BUILDSHARED VERBOSEMAKE COMPILER_TYPE AR ARFLAGS PGI_OLD_TEMPLATES SOFLAGS SET_MAKE RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CXXCPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1403,7 +1403,7 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in $CCC xlC_r CC g++
+  for ac_prog in $CCC xlC_r CC g++ pgCC icpc
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -1445,7 +1445,7 @@ fi
 fi
 if test -z "$CXX"; then
   ac_ct_CXX=$CXX
-  for ac_prog in $CCC xlC_r CC g++
+  for ac_prog in $CCC xlC_r CC g++ pgCC icpc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1990,6 +1990,11 @@ else
 fi;
 
 
+CXXFLAGS="$CXXFLAGS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS"
+
+CXXFLAGS=`echo $CXXFLAGS | sed 's/-g //; s/-O //; s/-O1 //; s/-O2 //; s/-O3 //'`
+
+
 
   echo "$as_me:$LINENO: checking for compiler type" >&5
 echo $ECHO_N "checking for compiler type... $ECHO_C" >&6
@@ -2218,6 +2223,61 @@ elif test $COMPILER_TYPE = "pgi" ; then
         CXXFLAGS="$CXXFLAGS -O0"
     fi
 
+    GOOD_CXXFLAGS="$CXXFLAGS"
+    CXXFLAGS="$CXXFLAGS --one_instantiation_per_object"
+    echo "$as_me:$LINENO: checking whether pgCC supports --one_instantiation_per_object" >&5
+echo $ECHO_N "checking whether pgCC supports --one_instantiation_per_object... $ECHO_C" >&6
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6 ; PGI_OLD_TEMPLATES="yes" ; debug_mode="no"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6 ; PGI_OLD_TEMPLATES="no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+    CXXFLAGS="$GOOD_CXXFLAGS"
+
     SOFLAGS="-shared"
 
     # Extract the first word of "ar", so it can be a program name with args.
@@ -2320,18 +2380,15 @@ fi
 
 fi
 
-CXXFLAGS=`echo $CXXFLAGS | sed 's/-g //; s/-O //; s/-O1 //; s/-O2 //; s/-O3 //'`
 if test $debug_mode = "yes" ; then
     CXXFLAGS="-g $CXXFLAGS -DDEBUG"
 else
     CXXFLAGS="-O2 $CXXFLAGS"
 fi
 
-CXXFLAGS="$CXXFLAGS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS"
 
-echo "$as_me:$LINENO: checking whether we can compile/link with \"$CXX $CXXFLAGS $LIBS\"." >&5
-echo $ECHO_N "checking whether we can compile/link with \"$CXX $CXXFLAGS $LIBS\".... $ECHO_C" >&6
-
+echo "$as_me:$LINENO: checking whether we can compile/link with \"$CXX $CXXFLAGS $LIBS\"" >&5
+echo $ECHO_N "checking whether we can compile/link with \"$CXX $CXXFLAGS $LIBS\"... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -4776,6 +4833,7 @@ s,@VERBOSEMAKE@,$VERBOSEMAKE,;t t
 s,@COMPILER_TYPE@,$COMPILER_TYPE,;t t
 s,@AR@,$AR,;t t
 s,@ARFLAGS@,$ARFLAGS,;t t
+s,@PGI_OLD_TEMPLATES@,$PGI_OLD_TEMPLATES,;t t
 s,@SOFLAGS@,$SOFLAGS,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@RANLIB@,$RANLIB,;t t
