Added boost::timer capability to internal mrnet timers.
The internal mrnet timer class will now use boost::timer::cpu_timer
if this timer is availible on the system (only availible on version
2.0 of the boost::timer api). If boost::timer is unavailible the old
timer will be used instead.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4521,6 +4521,7 @@ fi
 
 HAVE_SYSTEM_BOOST="no"
 HAVE_USER_BOOST="no"
+HAVE_BOOST_TIMER="no"
 if test "$BOOST_INCDIR" = "" ; then
     if test "${ac_cv_header_boost_shared_ptr_hpp+set}" = set; then
   echo "$as_me:$LINENO: checking for boost/shared_ptr.hpp" >&5
@@ -4664,6 +4665,148 @@ if test $ac_cv_header_boost_shared_ptr_hpp = yes; then
 fi
 
 
+    if test "${ac_cv_header_boost_timer_timer_hpp+set}" = set; then
+  echo "$as_me:$LINENO: checking for boost/timer/timer.hpp" >&5
+echo $ECHO_N "checking for boost/timer/timer.hpp... $ECHO_C" >&6
+if test "${ac_cv_header_boost_timer_timer_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_boost_timer_timer_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_timer_timer_hpp" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking boost/timer/timer.hpp usability" >&5
+echo $ECHO_N "checking boost/timer/timer.hpp usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <boost/timer/timer.hpp>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking boost/timer/timer.hpp presence" >&5
+echo $ECHO_N "checking boost/timer/timer.hpp presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <boost/timer/timer.hpp>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: present but cannot be compiled" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: boost/timer/timer.hpp: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: boost/timer/timer.hpp: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for boost/timer/timer.hpp" >&5
+echo $ECHO_N "checking for boost/timer/timer.hpp... $ECHO_C" >&6
+if test "${ac_cv_header_boost_timer_timer_hpp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_boost_timer_timer_hpp=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_boost_timer_timer_hpp" >&5
+echo "${ECHO_T}$ac_cv_header_boost_timer_timer_hpp" >&6
+
+fi
+if test $ac_cv_header_boost_timer_timer_hpp = yes; then
+  HAVE_BOOST_TIMER="yes"
+fi
+
+
 else
     as_ac_File=`echo "ac_cv_file_$BOOST_INCDIR/boost/shared_ptr.hpp" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $BOOST_INCDIR/boost/shared_ptr.hpp" >&5
@@ -4687,14 +4830,43 @@ if test `eval echo '${'$as_ac_File'}'` = yes; then
   HAVE_USER_BOOST="yes"
 fi
 
+    as_ac_File=`echo "ac_cv_file_$BOOST_INCDIR/boost/timer/timer.hpp" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $BOOST_INCDIR/boost/timer/timer.hpp" >&5
+echo $ECHO_N "checking for $BOOST_INCDIR/boost/timer/timer.hpp... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$BOOST_INCDIR/boost/timer/timer.hpp"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAVE_BOOST_TIMER="yes"
+fi
+
 fi
 
 
 
 
+
 STDCFLAGS="-D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS"
-CXXFLAGS="$CXXFLAGS $STDCFLAGS"
 CFLAGS="$CFLAGS $STDCFLAGS"
+if test "${HAVE_BOOST_TIMER}" = "yes" ; then
+    CXXFLAGS="$CXXFLAGS $STDCFLAGS -DUSE_BOOST_TIMER "
+else
+    CXXFLAGS="$CXXFLAGS $STDCFLAGS"
+fi
+
+
 
 CXXFLAGS=`echo $CXXFLAGS | sed 's/-g //; s/-O //; s/-O1 //; s/-O2 //; s/-O3 //'`
 CFLAGS=`echo $CFLAGS | sed 's/-g //; s/-O //; s/-O1 //; s/-O2 //; s/-O3 //'`
